### ISSUE TITLE
school in relations not found

### ISSUE THREAD

**Issue by Jakkajakka** [homtec/thenextis#34]
Hi,
"amenity=school" with multi buildings are together in a relations or closed building with in the centre the playground are also in a relation. Is not visible, found
schools in this link is not shown.
http://www.openstreetmap.org/#map=17/50.79178/3.18836
Gemeentelijke Basisschool Lauwe Wonderwijzer

thx

**Comment by homtec** [comment]
Can find it here:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/763536/183768762-4d7b1658-0c1f-4797-9ebf-f9fab8a49178.png">
